### ISSUE TITLE
Received fast shutdown request.

### ISSUE THREAD

**Issue by michailbrynard** [zalando/spilo#217]
We've been running patroni in production on kubernetes for one month now. Everything has been running smoothly, except there have been two instances where postgres on the master has "received a fast shutdown request" and gone down for a few seconds.

It happened today where postgres went down for 7 seconds with the following logs:
```
2018-03-14 13:14:03.129 UTC,,,22949,,5a96ecfb.59a5,4,,2018-02-28 17:55:07 UTC,,0,LOG,00000,"received fast shutdown request",,,,,,,,,""
2018-03-14 13:14:03.129 UTC,,,22949,,5a96ecfb.59a5,5,,2018-02-28 17:55:07 UTC,,0,LOG,00000,"aborting any active transactions",,,,,,,,,""
2018-03-14 13:14:03.129 UTC,"postgres","postgres",23274,"[local]",5a96ed0d.5aea,3,"idle",2018-02-28 17:55:25 UTC,5/0,0,FATAL,57P01,"terminating connection due to administrator command",,,,,,,,,"Patroni"
2018-03-14 13:14:03.129 UTC,"postgres","postgres",23274,"[local]",5a96ed0d.5aea,4,"idle",2018-02-28 17:55:25 UTC,,0,LOG,00000,"disconnection: session time: 331:18:37.530 user=postgres database=postgres host=[local]",,,,,,,,,"Patroni"
2018-03-14 13:14:03.130 UTC,"admin","postgres",26922,"10.24.4.84:44888",5aa516f4.692a,3,"idle",2018-03-11 11:45:56 UTC,6/0,0,FATAL,57P01,"terminating connection due to administrator command",,,,,,,,,""
2018-03-14 13:14:03.130 UTC,,,24311,,5a96ed59.5ef7,2,,2018-02-28 17:56:41 UTC,7/0,0,LOG,00000,"pg_cron scheduler shutting down",,,,,,,,,""
2018-03-14 13:14:03.131 UTC,"admin","postgres",26922,"10.24.4.84:44888",5aa516f4.692a,4,"idle",2018-03-11 11:45:56 UTC,,0,LOG,00000,"disconnection: session time: 73:28:07.094 user=admin database=postgres host=10.24.4.84 port=44888",,,,,,,,,""
2018-03-14 13:14:03.137 UTC,,,24309,,5a96ed59.5ef5,2,,2018-02-28 17:56:41 UTC,1/0,0,LOG,00000,"autovacuum launcher shutting down",,,,,,,,,""
2018-03-14 13:14:03.145 UTC,,,22949,,5a96ecfb.59a5,6,,2018-02-28 17:55:07 UTC,,0,LOG,00000,"worker process: bg_mon (PID 23067) exited with exit code 1",,,,,,,,,""
2018-03-14 13:14:03.145 UTC,,,23064,,5a96ecff.5a18,7992,,2018-02-28 17:55:11 UTC,,0,LOG,00000,"shutting down",,,,,,,,,""
2018-03-14 13:14:03.189 UTC,,,23064,,5a96ecff.5a18,7993,,2018-02-28 17:55:11 UTC,,0,LOG,00000,"checkpoint starting: shutdown immediate",,,,,,,,,""
2018-03-14 13:14:03.278 UTC,,,23064,,5a96ecff.5a18,7994,,2018-02-28 17:55:11 UTC,,0,LOG,00000,"checkpoint complete: wrote 968 buffers (0.1%); 0 transaction log file(s) added, 0 removed, 1 recycled; write=0.056 s, sync=0.006 s, total=0.092 s; sync files=95, longest=0.003 s, average=0.000 s; distance=8744 kB, estimate=32630 kB",,,,,,,,,""
2018-03-14 13:14:03.601 UTC,"standby","",23137,"10.24.3.27:40390",5a96ed02.5a61,3,"streaming 27/7F000098",2018-02-28 17:55:14 UTC,,0,LOG,00000,"disconnection: session time: 331:18:49.567 user=standby database= host=10.24.3.27 port=40390",,,,,,,,,"patroni-rehive-core-patroni-1"
2018-03-14 13:14:03.601 UTC,"standby","",23132,"10.24.8.56:42628",5a96ed01.5a5c,3,"streaming 27/7F000098",2018-02-28 17:55:13 UTC,,0,LOG,00000,"disconnection: session time: 331:18:50.169 user=standby database= host=10.24.8.56 port=42628",,,,,,,,,"patroni-rehive-core-patroni-2"
2018-03-14 13:14:03.874 UTC,,,24870,"10.24.4.153:41998",5aa9201b.6126,1,"",2018-03-14 13:14:03 UTC,,0,LOG,00000,"connection received: host=10.24.4.153 port=41998",,,,,,,,,""
2018-03-14 13:14:03.879 UTC,"admin","postgres",24870,"10.24.4.153:41998",5aa9201b.6126,2,"",2018-03-14 13:14:03 UTC,,0,FATAL,57P03,"the database system is shutting down",,,,,,,,,""
2018-03-14 13:14:03.881 UTC,,,24871,"10.24.4.153:42000",5aa9201b.6127,1,"",2018-03-14 13:14:03 UTC,,0,LOG,00000,"connection received: host=10.24.4.153 port=42000",,,,,,,,,""
2018-03-14 13:14:03.881 UTC,"admin","postgres",24871,"10.24.4.153:42000",5aa9201b.6127,2,"",2018-03-14 13:14:03 UTC,,0,FATAL,57P03,"the database system is shutting down",,,,,,,,,""
.
.
.
2018-03-14 13:14:10.020 UTC,"admin","postgres",24989,"10.24.5.148:41262",5aa92022.619d,2,"",2018-03-14 13:14:10 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-03-14 13:14:10.234 UTC,,,24990,"10.24.5.148:41268",5aa92022.619e,1,"",2018-03-14 13:14:10 UTC,,0,LOG,00000,"connection received: host=10.24.5.148 port=41268",,,,,,,,,""
2018-03-14 13:14:10.252 UTC,"admin","postgres",24990,"10.24.5.148:41268",5aa92022.619e,2,"",2018-03-14 13:14:10 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-03-14 13:14:10.266 UTC,,,24991,"10.24.5.148:41270",5aa92022.619f,1,"",2018-03-14 13:14:10 UTC,,0,LOG,00000,"connection received: host=10.24.5.148 port=41270",,,,,,,,,""
2018-03-14 13:14:10.266 UTC,"admin","postgres",24991,"10.24.5.148:41270",5aa92022.619f,2,"",2018-03-14 13:14:10 UTC,,0,FATAL,57P03,"the database system is starting up",,,,,,,,,""
2018-03-14 13:14:10.327 UTC,,,24883,,5aa9201e.6133,4,,2018-03-14 13:14:06 UTC,1/0,0,LOG,00000,"consistent recovery state reached at 27/7F000098",,,,,,,,,""
2018-03-14 13:14:10.327 UTC,,,24883,,5aa9201e.6133,5,,2018-03-14 13:14:06 UTC,1/0,0,LOG,00000,"invalid record length at 27/7F000098: wanted 24, got 0",,,,,,,,,""
2018-03-14 13:14:10.329 UTC,,,24880,,5aa9201e.6130,2,,2018-03-14 13:14:06 UTC,,0,LOG,00000,"database system is ready to accept read only connections",,,,,,,,,""
2018-03-14 13:14:10.719 UTC,,,25010,"10.24.5.147:44066",5aa92022.61b2,1,"",2018-03-14 13:14:10 UTC,,0,LOG,00000,"connection received: host=10.24.5.147 port=44066",,,,,,,,,""
2018-03-14 13:14:10.734 UTC,"admin","postgres",25010,"10.24.5.147:44066",5aa92022.61b2,2,"authentication",2018-03-14 13:14:10 UTC,3/1,0,LOG,00000,"connection authorized: user=admin database=postgres SSL enabled (protocol=TLSv1.2, cipher=ECDHE-RSA-AES256-GCM-SHA384, compression=off)",,,,,,,,,""
2018-03-14 13:14:10.738 UTC,"admin","postgres",25010,"10.24.5.147:44066",5aa92022.61b2,3,"idle",2018-03-14 13:14:10 UTC,,0,LOG,00000,"disconnection: session time: 0:00:00.018 user=admin database=postgres host=10.24.5.147 port=44066",,,,,,,,,""
```   
  
Do you have any idea where the "fast shutdown request" could be coming from? We never experienced this issue when running the standard postgresql docker container in the past, only recently with spilo.

**Comment by CyberDem0n** [comment]
Hi @michailbrynard 

I think it was shut down by Patroni for some reason.
More details should be in the Patroni log:
```
$ kubectl logs patroni-rehive-core-patroni-0
```

Do you run it with etcd or just with kubernetes api?

If the master pod can't update leader lock it restarts postgres in read-only.  I think this is what happened, but as I told before, please have a look into Patroni log.

**Comment by michailbrynard** [comment]
Hi @CyberDem0n 

I think you are right about it being a DCS communication issue. Looking at the patroni logs (edited), I see:

```
2018-03-14 13:14:02,853 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff924dea9e8>, 'Connection to 10.27.240.1 timed out. (connect timeout=1)')': /api/v1/namespaces/rehive-core/endpoints?labelSelector=release%3Dpatroni-rehive-core%2Capp%3Dpatroni%2Capplication%3Dpatroni%2Ccluster%3Dpatroni-rehive-core-patroni
2018-03-14 13:14:03,077 ERROR: get_cluster
.
.
.
Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/kubernetes.py", line 135, in _load_cluster response = self.retry(self._api.list_namespaced_pod, self._namespace, label_selector=self._label_selector) File "/usr/local/lib/python3.5/dist-packages/patroni/dcs/kubernetes.py", line 97, in retry return self._retry.copy()(*args, **kwargs) File "/usr/local/lib/python3.5/dist-packages/patroni/utils.py", line 263, in __call__ raise RetryFailedError("Exceeded retry deadline") patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2018-03-14 13:14:03,080 ERROR: Error communicating with DCS
2018-03-14 13:14:03,856 INFO: DCS is not accessible
2018-03-14 13:14:03,858 WARNING: Loop time exceeded, rescheduling immediately.
.
.
.
2018-03-14 13:14:18.000 UTC server promoting
2018-03-14 13:14:18,468 INFO: cleared rewind state after becoming the leader
2018-03-14 13:14:18,493 INFO: promoted self to leader because i had the session lock
2018-03-14 13:14:18,375 INFO: Lock owner: patroni-rehive-core-patroni-0; I am patroni-rehive-core-patroni-0
2018-03-14 13:14:18,376 INFO: establishing a new patroni connection to the postgres cluster
```   
    
We are using Kubernetes as the DCS as I had some issues getting etcd setup properly and going with Kubernetes seems great in terms of keeping maintenance to a minimum. We are running on GKE, do you think this is as a result of downtime in their Kubernetes API?

**Comment by CyberDem0n** [comment]
Yeah, it really looks like a short downtime of k8s API on GKE. It would be great to get from the logs how long it wasn't accessible and adjust retry_timeout and ttl accordingly.

```bash
$ kubectl exec -ti patroni-rehive-core-patroni-0 su postgres # exec into container

postgres@patroni-rehive-core-patroni-0:~$ patronictl edit-config $SCOPE # it will open vi session with cluster-wide configuration
```
Configuration is in yaml format. `ttl`, `loop_wait` and `retry_timeout` are at the top level.
There is a dependency between all three parameters: `ttl >= loop_wait + retry_timeout * 2`, that mean if you want to increase retry_timeout, at the same time you also should either increase ttl, or decrease loop_wait.

For example if you set retry_timeout to 20 seconds and leave loop_wait as it was (10 seconds), you should increase ttl to 50 seconds.

Such change will improve resilience to k8s API failures, but at the same time it will make detection of leader failures longer, 50s instead of 30s. So it is always a trade off, but in our experience usually it is happening not very often, that k8s Node is going down due to hardware failures. What is usually happens, that a Node is being shut down gracefully, with notifying all Pods and containers running on this it by sending SIGTERM. In this case Patroni will do a fast shutdown of postgres and voluntarily release a leader lock after that. Other pods will see it immediately and one of them will become a new leader. Effectively this is a switchover. 

BTW, even if you run Patroni on Kubernetes with etcd, you'll eventually get to situation which is even worse, because in this case Patroni will use a callbacks in order to set label with the current role on the pod and to update leader endpoint.
This script (which sets labels and updates endpoint) is also calling k8s api and retrying up to 10 times in case of failure. If API is not accessible, we will end up in situation when role label is incorrect and endpoint containing a wrong IP. Basically it is a situation that you have the master, but the service will not forward a traffic to it.

**Comment by michailbrynard** [comment]
Just an update on this: since upgrading to the following settings two weeks ago, we've not yet seen the issue reappear on GKE:

> retry_timeout: 20
> loop_wait: 10
> ttl: 50

Thanks for the advice!
