### ISSUE TITLE
Permission issue with postgres.yml on Kubernetes

### ISSUE THREAD

**Issue by JohnnyQQQQ** [zalando/spilo#271]
I tried to setup a Patroni cluster using spilo and ran into an issue on start-up. 

```
decompressing spilo image...
2018-10-30 10:45:32,229 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2018-10-30 10:45:33,104 - bootstrapping - INFO - Looks like your running openstack
2018-10-30 10:45:33,124 - bootstrapping - INFO - Configuring bootstrap
2018-10-30 10:45:33,124 - bootstrapping - INFO - Configuring wal-e
2018-10-30 10:45:33,124 - bootstrapping - INFO - Configuring pgbouncer
2018-10-30 10:45:33,124 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2018-10-30 10:45:33,124 - bootstrapping - INFO - Configuring patroni
2018-10-30 10:45:33,135 - bootstrapping - INFO - Writing to file /home/postgres/postgres.yml
2018-10-30 10:45:33,136 - bootstrapping - INFO - Configuring patronictl
2018-10-30 10:45:33,136 - bootstrapping - INFO - Configuring certificate
2018-10-30 10:45:33,136 - bootstrapping - INFO - Generating ssl certificate
2018-10-30 10:45:33,178 - bootstrapping - INFO - Configuring pam-oauth2
2018-10-30 10:45:33,178 - bootstrapping - INFO - No PAM_OAUTH2 configuration was specified, skipping
2018-10-30 10:45:33,178 - bootstrapping - INFO - Configuring crontab
2018-10-30 10:45:33,436 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2018-10-30 10:45:33,437 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2018-10-30 10:45:33,437 INFO Included extra file "/etc/supervisor/conf.d/patroni.conf" during parsing
2018-10-30 10:45:33,437 INFO Included extra file "/etc/supervisor/conf.d/pgq.conf" during parsing
2018-10-30 10:45:33,445 INFO RPC interface 'supervisor' initialized
2018-10-30 10:45:33,446 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-10-30 10:45:33,446 INFO supervisord started with pid 1
2018-10-30 10:45:34,448 INFO spawned: 'cron' with pid 30
2018-10-30 10:45:34,450 INFO spawned: 'patroni' with pid 31
2018-10-30 10:45:34,452 INFO spawned: 'pgq' with pid 32
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    load_entry_point('patroni==1.4.4', 'console_scripts', 'patroni')()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 179, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 146, in patroni_main
    patroni = Patroni()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 24, in __init__
    self.config = Config()
  File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 67, in __init__
    self._local_configuration = self._load_config_file()
  File "/usr/local/lib/python3.6/dist-packages/patroni/config.py", line 96, in _load_config_file
    with open(self._config_file) as f:
PermissionError: [Errno 13] Permission denied: '/home/postgres/postgres.yml'
2018-10-30 10:45:34,859 INFO exited: patroni (exit status 1; not expected)
```

When I exec into the container to check the permissions I get the following result

```
# ls -lah
total 32K
drwxr-xr-x 4 postgres postgres 4.0K Oct 30 10:45 .
drwxr-xr-x 3 root     root     4.0K Jun 26 13:17 ..
drwxr-x--- 3 root     root     4.0K Oct 30 10:45 .config
drwxr-xr-x 4 root     root     4.0K Oct 30 10:45 pgdata
-rw-r--r-- 1 postgres postgres  174 Jun 26 13:07 pgq_ticker.ini
-rw-r----- 1 root     root     3.0K Oct 30 10:45 postgres.yml
-rw-r----- 1 root     root     1.1K Oct 30 10:45 server.crt
-rw------- 1 postgres root     1.7K Oct 30 10:45 server.key
```

This is the `StatefulSet` I use  
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: &cluster_name postgres-patroni
  labels:
    application: patroni
    cluster-name: *cluster_name
spec:
  replicas: 3
  serviceName: *cluster_name
  selector:
    matchLabels:
      application: patroni
      cluster-name: *cluster_name
  template:
    metadata:
      labels:
        application: patroni
        cluster-name: *cluster_name
    spec:
      serviceAccountName: postgres-patroni
      containers:
      - name: *cluster_name
        image: registry.opensource.zalan.do/acid/spilo-10:1.4-p11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008
          protocol: TCP
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /home/postgres/pgdata
          name: pgdata
        env:
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PATRONI_KUBERNETES_USE_ENDPOINTS
          value: 'true'
        - name: PATRONI_KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PATRONI_KUBERNETES_LABELS
          value: '{application: patroni, cluster-name: postgres-patroni}'
        - name: PATRONI_SUPERUSER_USERNAME
          value: postgres
        - name: PATRONI_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: superuser-password
        - name: PATRONI_REPLICATION_USERNAME
          value: standby
        - name: PATRONI_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: *cluster_name
              key: replication-password
        - name: PATRONI_SCOPE
          value: *cluster_name
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /home/postgres/pgdata/pgroot/data
        - name: PATRONI_POSTGRESQL_PGPASS
          value: /tmp/pgpass
        - name: PATRONI_POSTGRESQL_LISTEN
          value: '0.0.0.0:5432'
        - name: PATRONI_RESTAPI_LISTEN
          value: '0.0.0.0:8008'
        - name: PGROOT
          value: /home/postgres/pgdata/pgroot
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata
  volumeClaimTemplates:
  - metadata:
      labels:
        application: spilo
        spilo-cluster: *cluster_name
      annotations:
        volume.beta.kubernetes.io/storage-class: ssd
      name: pgdata
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ssd
      resources:
        requests:
          storage: 50Gi
```

I'm not sure what the Issue is, as I already used this StatefulSet to deploy a postgres-cluster on another kubernetes cluster. The Storage is different, but I'm not sure if this could be an issue.

**Comment by JohnnyQQQQ** [comment]
After setting the right permissions I get another error

```
PermissionError: [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'
2018-10-30 12:15:19,321 INFO exited: patroni (exit status 1; not expected)
```

I think I'm missing out something important here..

**Comment by CyberDem0n** [comment]
You have to setup a service account.
Like [here](https://github.com/zalando/patroni/blob/master/kubernetes/patroni_k8s.yaml#L125-L186) or use the helm chart: https://github.com/helm/charts/tree/master/incubator/patroni

**Comment by JohnnyQQQQ** [comment]
I have created one but didn't pasted it into the issue 

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-patroni

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-patroni
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  # the following three privileges are necessary only when using endpoints
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-patroni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-patroni
subjects:
- kind: ServiceAccount
  name: postgres-patroni
```

**Comment by CyberDem0n** [comment]
It looks like umask is set to something different from `0002`...
I have no other explanation why you get such permissions:
```
# ls -lah
total 32K
drwxr-xr-x 4 postgres postgres 4.0K Oct 30 10:45 .
drwxr-xr-x 3 root     root     4.0K Jun 26 13:17 ..
drwxr-x--- 3 root     root     4.0K Oct 30 10:45 .config
drwxr-xr-x 4 root     root     4.0K Oct 30 10:45 pgdata
-rw-r--r-- 1 postgres postgres  174 Jun 26 13:07 pgq_ticker.ini
-rw-r----- 1 root     root     3.0K Oct 30 10:45 postgres.yml
-rw-r----- 1 root     root     1.1K Oct 30 10:45 server.crt
-rw------- 1 postgres root     1.7K Oct 30 10:45 server.key
```

This is what I have:
```
$ ls -alh
total 56K
drwxr-xr-x 5 postgres postgres 4.0K Oct 30 14:39 .
drwxr-xr-x 6 root     root     4.0K Aug 14 13:50 ..
drwxr-xr-x 3 root     root     4.0K Aug 14 13:50 .config
drwxr-xr-x 4 root     root     4.0K Aug 14 13:50 etc
drwxrwxrwx 5 root     root     4.0K Aug 10  2017 pgdata
-rw------- 1 postgres postgres   94 Aug 14 14:28 pgpass
-rw-r--r-- 1 postgres postgres  174 Aug 14 11:04 pgq_ticker.ini
-rw-r--r-- 1 root     root     4.2K Aug 14 13:50 postgres.yml
-rw-r--r-- 1 root     root     1.1K Aug 14 13:50 server.crt
-rw------- 1 postgres root     1.7K Aug 14 13:50 server.key
```

And I have the strong feeling that /var/run/secrets/kubernetes.io/serviceaccount/token is suffering from the same problem.

**Comment by JohnnyQQQQ** [comment]
Yeah you're right, it's `0027`, is there any way to set it?

**Comment by JohnnyQQQQ** [comment]
Issue is related to our cloud provider, so I close it, thank you @CyberDem0n
