### ISSUE TITLE
get_provider exception list doesn't include ReadTimeout

### ISSUE THREAD

**Issue by IlyaSemenov** [zalando/spilo#333]
I have a non-cloud VDS node/pod where patroni fails to start in the container due to crash in `configure_spilo.py`:

```
decompressing spilo image...
2019-04-22 17:01:48,719 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='169.254.169.254', port=80): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scripts/configure_spilo.py", line 891, in <module>
    main()
  File "/scripts/configure_spilo.py", line 791, in main
    provider = os.environ.get('DEVELOP', '').lower() in ['1', 'true', 'on'] and PROVIDER_LOCAL or get_provider()
  File "/scripts/configure_spilo.py", line 307, in get_provider
    r = requests.get('http://169.254.169.254', timeout=2)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Read timed out. (read timeout=2)
2019-04-22 17:01:51,083 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2019-04-22 17:01:51,084 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2019-04-22 17:01:51,084 INFO Included extra file "/etc/supervisor/conf.d/patroni.conf" during parsing
2019-04-22 17:01:51,084 INFO Included extra file "/etc/supervisor/conf.d/pgq.conf" during parsing
2019-04-22 17:01:51,096 INFO RPC interface 'supervisor' initialized
2019-04-22 17:01:51,096 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-04-22 17:01:51,097 INFO supervisord started with pid 1
2019-04-22 17:01:52,100 INFO spawned: 'cron' with pid 20
2019-04-22 17:01:52,103 INFO spawned: 'patroni' with pid 21
2019-04-22 17:01:52,111 INFO spawned: 'pgq' with pid 22
Usage: /usr/local/bin/patroni config.yml
	Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2019-04-22 17:01:53,500 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-04-22 17:01:53,500 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-04-22 17:01:53,500 INFO success: pgq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-04-22 17:01:53,500 INFO exited: patroni (exit status 1; not expected)
2019-04-22 17:01:54,504 INFO spawned: 'patroni' with pid 29
Usage: /usr/local/bin/patroni config.yml
	Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2019-04-22 17:01:54,942 INFO exited: patroni (exit status 1; not expected)
2019-04-22 17:01:55,945 INFO spawned: 'patroni' with pid 33
Usage: /usr/local/bin/patroni config.yml
	Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2019-04-22 17:01:57,404 INFO success: patroni entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-04-22 17:01:57,404 INFO exited: patroni (exit status 1; not expected)
2019-04-22 17:01:58,407 INFO spawned: 'patroni' with pid 37
Usage: /usr/local/bin/patroni config.yml
	Patroni may also read the configuration from the PATRONI_CONFIGURATION environment variable
2019-04-22 17:01:58,707 INFO exited: patroni (exit status 1; not expected)
2019-04-22 17:01:59,710 INFO spawned: 'patroni' with pid 41
^C
```

This is probably caused by the fact that `requests.exceptions.ReadTimeout` is not listed in the exceptions here:

https://github.com/zalando/spilo/blob/074468282d53992f37db8c420070285adbc32e44/postgres-appliance/scripts/configure_spilo.py#L319-L321

Luckily I was able to overcome that with `DEVELOP=1`, however it's clearly not the best solution (for starters, `DEVELOP=1` may have unwanted side effects, if not now then possibly in future).

What I would expect is:
1) `ReadTimeout` being a legitimate cause for falling back to local deploy detection
2) Being able to explicitly define environment and bypass auto-detect with something like `SPILO_PROVIDER=local`

**Comment by CyberDem0n** [comment]
Hi @IlyaSemenov,

sure, please feel free to contribute PR fixing your problem.
