### ISSUE TITLE
Issues with Azure Kubernetes Service with AAD Pod Identity

### ISSUE THREAD

**Issue by keyz182** [zalando/spilo#542]
I'm using the `registry.opensource.zalan.do/acid/spilo-13:2.0-p2` image via the postgres operator. It appears that when using [AAD Pod Indentity](https://github.com/Azure/aad-pod-identity) on an Azure Kubernetes Service instance, some of the provider detection logic is failing. If I override `SPILO_PROVIDER` to `local` things work. 

```
2021-01-14T16:28:17.428933191Z 2021-01-14 16:28:17,428 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2021-01-14T16:28:17.443798096Z Traceback (most recent call last):
2021-01-14T16:28:17.443810896Z   File "/scripts/configure_spilo.py", line 1012, in <module>
2021-01-14T16:28:17.443814096Z     main()
2021-01-14T16:28:17.443820197Z   File "/scripts/configure_spilo.py", line 890, in main
2021-01-14T16:28:17.443823897Z     placeholders = get_placeholders(provider)
2021-01-14T16:28:17.443827297Z   File "/scripts/configure_spilo.py", line 598, in get_placeholders
2021-01-14T16:28:17.443830697Z     placeholders['instance_data'] = get_instance_metadata(provider)
2021-01-14T16:28:17.443833797Z   File "/scripts/configure_spilo.py", line 391, in get_instance_metadata
2021-01-14T16:28:17.443837298Z     openstack_metadata = requests.get(url, timeout=5).json()
2021-01-14T16:28:17.443839498Z   File "/usr/lib/python3/dist-packages/requests/models.py", line 884, in json
2021-01-14T16:28:17.443841798Z     self.content.decode(encoding), **kwargs
2021-01-14T16:28:17.443843998Z   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
2021-01-14T16:28:17.443846198Z     return _default_decoder.decode(s)
2021-01-14T16:28:17.443848298Z   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
2021-01-14T16:28:17.443850498Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2021-01-14T16:28:17.443852598Z   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
2021-01-14T16:28:17.443854798Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2021-01-14T16:28:17.443857098Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Doing some testing from within a pod, I can see this:
```
Python 3.7.9 (default, Nov 18 2020, 14:10:47) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get("http://169.254.169.254/openstack/latest/meta_data.json")
>>> r.ok
True
>>> r.status_code
200
>>> r.text
'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type="text/css">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id="header"><h1>Server Error</h1></div>\r\n<div id="content">\r\n <div class="content-container"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n'
>>>
```

I've tracked this down to an issue I've just reported in AAD-POD-Identity (https://github.com/Azure/aad-pod-identity/issues/943). I'm also reporting here in case anyone else encounters the issue. It may make sense though to catch json decoding errors in that section and fall back to local. It wouldn't fix the cause of the issue, but it would be a fallback.

**Comment by CyberDem0n** [comment]
When running on K8s all dancing around the instance metadata is not required and most of these results are discarded anyway.
Yes, catching the exception and returning `PROVIDER_LOCAL` will do the job. Would you like to open a PR with the fix?
