### ISSUE TITLE
seteuid: Operation not permitted Error in PG cluster

### ISSUE THREAD

**Issue by neelasha-09** [zalando/spilo#551]
Hi,

We see below error while running postgres-operator-cluster  on OpenShift environment.

Image: `spilo-13:2.0-p3`

```shell
[crc@eaas-crc postgres-operator]$ oc logs -f postgres-service-01-0 -c postgres
2021-02-05 11:23:06,997 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2021-02-05 11:23:08,089 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
2021-02-05 11:23:08,091 - bootstrapping - INFO - No meta-data available for this provider
2021-02-05 11:23:08,091 - bootstrapping - INFO - Looks like your running local
2021-02-05 11:23:08,168 - bootstrapping - INFO - Configuring crontab
2021-02-05 11:23:08,169 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2021-02-05 11:23:08,186 - bootstrapping - INFO - Configuring pgqd
2021-02-05 11:23:08,187 - bootstrapping - INFO - Configuring log
2021-02-05 11:23:08,187 - bootstrapping - INFO - Configuring certificate
2021-02-05 11:23:08,188 - bootstrapping - WARNING - Private key already exists, not overwriting. (Use option --force if necessary)
2021-02-05 11:23:08,188 - bootstrapping - INFO - Configuring wal-e
2021-02-05 11:23:08,188 - bootstrapping - INFO - Configuring bootstrap
2021-02-05 11:23:08,188 - bootstrapping - INFO - Configuring patroni
2021-02-05 11:23:08,197 - bootstrapping - INFO - Writing to file /run/postgres.yml
Traceback (most recent call last):
  File "/scripts/configure_spilo.py", line 1022, in <module>
    main()
  File "/scripts/configure_spilo.py", line 953, in main
    adjust_owner(placeholders, PATRONI_CONFIG_FILE, gid=-1)
  File "/scripts/configure_spilo.py", line 68, in adjust_owner
    os.chown(resource, uid, gid)
PermissionError: [Errno 1] Operation not permitted: '/run/postgres.yml'
seteuid: Operation not permitted
seteuid: Operation not permitted
```

Files inside container:
```shell
postgres@postgres-service-01-0:/run$ ll
total 8
drwxrwxr-x. 1      101 root        109 Feb  5 11:23 ./
drwxr-xr-x. 1 root     root         51 Feb  5 11:23 ../
drwxr-xr-x. 2 postgres root          6 Feb  5 11:23 certs/
drwxr-xr-x. 3 postgres root         22 Feb  5 11:23 cron/
-rw-r--r--. 1 postgres root          5 Feb  5 11:42 crond.pid
drwxrwxrwt. 1      101 root          6 Nov 19 13:07 lock/
drwxrwxr-x. 1      101 root         18 Nov 19 13:07 mount/
-rw-r--r--. 1 postgres root       3115 Feb  5 11:23 postgres.yml
drwxrwsrwx. 2 root     1000620000    6 Feb  5 11:23 postgresql/
drwxr-xr-x. 4 root     root         80 Feb  5 11:23 secrets/
drwxr-xr-x. 4 postgres root         30 Feb  5 11:23 service/
drwxrwxr-x. 1      101 root         23 Nov 25 22:25 systemd/
drwxrwxrwt. 2 postgres root          6 Feb  5 11:42 tmp/
-rw-rw-r--. 1      101 root          0 Nov 19 13:07 utmp 

postgres@postgres-service-01-0:/run/postgresql$ id
uid=1000620000(postgres) gid=0(root) groups=0(root),1000620000

```

The func. was changed on PG in place upgrade PR commit:
https://github.com/zalando/spilo/commit/bb6ab228d04487920c5c7cabfedf4f0a9e9fc7af#diff-e4dcf964214d58d733ae9874d4a2ab4b8e9eb99213307e1666af5dad21a326bbR66

https://github.com/zalando/spilo/blob/2.0-p3/postgres-appliance/scripts/configure_spilo.py#L953
            `adjust_owner(placeholders, PATRONI_CONFIG_FILE, gid=-1)`

We suggest changes to function and avoid `chown` when not mandatory
```python
def adjust_owner(placeholders, resource, uid=None, gid=None):
    st = os.stat(placeholders['PGHOME'])
    if uid is None:
        uid = st.st_uid
    if gid is None:
        gid = st.st_gid
    os.chown(resource, uid, gid)
``` 
Please note : The function `write_patroni_config` did not fail but only `adjust_owner` failed.

Maybe the chown should be done conditionally, like here:
https://github.com/zalando/spilo/blob/2.0-p3/postgres-appliance/launch.sh#L22  

Until this change, Postgres was working fine on OCP environment.

Regards,
Neelam Sharma

**Comment by CyberDem0n** [comment]
please open a PR
