### ISSUE TITLE
ConnectTimeoutError problem

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#590]
Hi,

I have a Kubernetes cluster on Virtual Box managed by this my project:
https://github.com/sasadangelo/k8s-cluster

I built the default Spilo docker image and uploaded it on my DockerHUB sasadangelo/spilo. Then I used this manifest to deploy Spilo on Kubernetes:
https://github.com/zalando/spilo/blob/master/kubernetes/spilo_kubernetes.yaml

the only change I applied is to comment on the AWS line and remove the PersistentVolume since the standard class doesn't exist and I wanted to remove any complication.

However, I got the errors below. My understanding is that there is a Service-config with an endpoint associated with it. Spilo uses the endpoint associated with this service as key-value DB in place of Etcd (not sure if I understand it correctly).
However, it seems that to elect the leader it tries to access Kubernetes API and it git the errors below.

I think I need some permission that there are not in the manifest.

Can anyone help with this?

2021-06-30 15:14:42,124 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa15240>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)')': /api/v1/namespaces/default/pods?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01
2021-06-30 15:14:42,125 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa157b8>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)')': /api/v1/namespaces/default/endpoints?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01
2021-06-30 15:14:44,629 ERROR: Request to server https://192.168.205.10:6443 failed: MaxRetryError("HTTPSConnectionPool(host='192.168.205.10', port=6443): Max retries exceeded with url: /api/v1/namespaces/default/pods?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa15780>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)'))",)
2021-06-30 15:14:44,631 ERROR: Request to server https://192.168.205.10:6443 failed: MaxRetryError("HTTPSConnectionPool(host='192.168.205.10', port=6443): Max retries exceeded with url: /api/v1/namespaces/default/endpoints?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa15278>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)'))",)
2021-06-30 15:14:45,678 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
2021-06-30 15:14:45,682 ERROR: ObjectCache.run TypeError("unsupported operand type(s) for -: 'NoneType' and 'float'",)
2021-06-30 15:14:48,209 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa38a90>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)')': /api/v1/namespaces/default/pods?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01
2021-06-30 15:14:48,281 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa38e10>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)')': /api/v1/namespaces/default/endpoints?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01
2021-06-30 15:14:49,624 ERROR: get_cluster
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 701, in _load_cluster
    self._wait_caches(stop_time)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 693, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'
2021-06-30 15:14:49,625 WARNING: Can not get cluster from dcs
2021-06-30 15:14:50,713 ERROR: Request to server https://192.168.205.10:6443 failed: MaxRetryError("HTTPSConnectionPool(host='192.168.205.10', port=6443): Max retries exceeded with url: /api/v1/namespaces/default/pods?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa15518>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)'))",)
2021-06-30 15:14:50,784 ERROR: Request to server https://192.168.205.10:6443 failed: MaxRetryError("HTTPSConnectionPool(host='192.168.205.10', port=6443): Max retries exceeded with url: /api/v1/namespaces/default/endpoints?labelSelector=application%3Dspilo%2Cspilo-cluster%3Dzalandodemo01 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f501aa38b70>, 'Connection to 192.168.205.10 timed out. (connect timeout=2.5)'))",)
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 701, in _load_cluster
    self._wait_caches(stop_time)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 693, in _wait_caches
    raise RetryFailedError('Exceeded retry deadline')
patroni.utils.RetryFailedError: 'Exceeded retry deadline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 46, in load_dynamic_configuration
    cluster = self.dcs.get_cluster()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 664, in get_cluster
    cluster = self._load_cluster()
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/kubernetes.py", line 766, in _load_cluster
    raise KubernetesError('Kubernetes API is not responding properly')
patroni.dcs.kubernetes.KubernetesError: 'Kubernetes API is not responding properly'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 33, in <module>
    sys.exit(load_entry_point('patroni==2.0.2', 'console_scripts', 'patroni')())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 170, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 138, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 98, in abstract_main
    controller = cls(config)
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 31, in __init__
    self.load_dynamic_configuration()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__init__.py", line 57, in load_dynamic_configuration
    time.sleep(5)

**Comment by sasadangelo** [comment]
Let me add what I am trying to achieve.
I manage a Patroni solution on bare metal and I need to port it on Kubernetes.
So I decided to start playing a bit with stuff already available open-source.
My goal is to deploy Spilo on three workers and try to simulate the following scenarios manually:
- fresh deploy
- failover scenarios with one node down
- PostgreSQL minor upgrade
- PostgreSQL major upgrade
- migration from an already existing cluster

However, I am stuck with the problem above. I hope you can help me to solve it, but also address me to some documentation to run manually the mentioned scenario. 

The next step is to try to use Zalando PostgreSQL Operator to automate the scenario above. For PostgreSQL Operator I already know there is a lot of docs on its own git repo.

**Comment by CyberDem0n** [comment]
Patroni want's to talk with K8s API. Its address is stored in the KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT environment variables.

Since 192.168.205.10:6443 isn't accessible from the spilo pod you get the above exceptions.

You need to figure why it isn't accessible or why environment variables maybe pointing to the wrong address.

**Comment by sasadangelo** [comment]
Thank you for the reply. I'll try your suggestion.

**Comment by sasadangelo** [comment]
Hi again,

There is something I don't understand. Basically, I have three nodes and the master is on 192.168.205.10/10.0.2.15.
If I give the command ```kubectl get svc```I got:

```
kubernetes             ClusterIP   10.96.0.1       <none>        443/TCP    21d 
```

So I set this host hardcoded in spilo_kubernetes.yml just to have it working:

```
        - name: KUBERNETES_SERVICE_HOST
          value: '10.96.0.1'
```

I delete/deploy the manifest but I still have the issue. If I run:
```
root@zalandodemo01-0:/home/postgres# echo $KUBERNETES_SERVICE_HOST
10.96.0.1
root@zalandodemo01-0:/home/postgres# echo $KUBERNETES_SERVICE_PORT
443
```

To test if the Pod works fine with Kubernetes API service I created this script:
```
KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/default/pods/$HOSTNAME
```

and it works fine. So why Patroni still use the public IP of my master node? Where did it get this value? I looked at code and it use the two variables KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT, so this doesn't make sense to me.

**Comment by sasadangelo** [comment]
I found where that address come from:

```
kubectl get endpoints
NAME            ENDPOINTS             AGE
kubernetes      192.168.205.10:6443   144m
```

this is because I configured my vagrant machine with IPs:
192.168.205.10 (master)
192.168.205.11 (worker)
192.168.205.12 (worker)

the problem is that it is not pingable from the Pod

**Comment by CyberDem0n** [comment]
Please try to set `KUBERNETES_BYPASS_API_SERVICE` to `false`.
