### ISSUE TITLE
QUESTION: hostname in postgres.yml instead of IPs

### ISSUE THREAD

**Issue by sasadangelo** [zalando/spilo#627]
Hi,

I am implementing a PR to support SSL REST API. For this SSL I need client verification. My problem is the following. If I run:
```
patronictl list
```

I see this:
```
+ Cluster: cfdb-ccdb (7008147023533715528) ---------+----+-----------+
| Member      | Host            | Role    | State   | TL | Lag in MB |
+-------------+-----------------+---------+---------+----+-----------+
| cfdb-ccdb-0 | 192.168.230.41  | Replica | running |  1 |         0 |
| cfdb-ccdb-1 | 192.168.140.21  | Leader  | running |  1 |           |
| cfdb-ccdb-2 | 192.168.235.223 | Replica | running |  1 |         0 |
+-------------+-----------------+---------+---------+----+-----------+
```

As you can see I have IPs instead of hostname like, for example, <my hostname>.<namespace>.svc.cluster.local. The reason is that in ```configure_spilo.py``` we have:
```
restapi:
  listen: ':{{APIPORT}}'
  connect_address: {{instance_data.ip}}:{{APIPORT}}
```

As you can notice, by default, IP is used. The problem is that when a patronictl command is given, the IP is used and I cannot put IPs with wild cards in a certificate. I can put a single IP but every deploys it changes. I could use all possible IPs but they are too much.

I need a way to have a hostname there instead of IP. How I can achieve that?

**Comment by CyberDem0n** [comment]
The main reason why we use IPs everywhere - because we want to avoid "It's always DNS" problems (I would recommend to google it) as much as possible.
Right now there is no way to specify `{{instance_data.ip}}` from outside, it shouldn't be hard to add it though.

**Comment by sasadangelo** [comment]
I'll try to Google it. One problem, for sure, with IP is SSL with client verification when you need to specify IP in SAN and you work with Kubernetes. If your CICDR is 192.168.2.0/8 you need to add 256 IPs to the SAN list (there is no wild card for IPs). This becomes even bigger for CICDR like 192.168.0.0/16. You understand it's not feasible.
The only solution is to have hostnames.
Now I would like to have something like:
* cfdb-ccdb-0.<namespace>.svc.cluster.local
* cfdb-ccdb-1.<namespace>.svc.cluster.local
* cfdb-ccdb-2.<namespace>.svc.cluster.local

where cfdb-ccdb is the name of my StetefulSet.
Can you just give me a few references on how this could be implemented? At the moment I can disable client verification and just let IPs there. In the meanwhile, I put this in our backlog to implement in the next months (before December for sure)

**Comment by CyberDem0n** [comment]
> Can you just give me a few references on how this could be implemented? 

There is a function that builds the instance metadata dict, you can set the 'ip' to a custom value from `CONNECT_ADDRESS` env variable.
https://github.com/zalando/spilo/blob/4c02a6dd1970307d34001089106b8417fa0554c2/postgres-appliance/scripts/configure_spilo.py#L379-L410

**Comment by sasadangelo** [comment]
Thank you I will give it a look as soon as I have more bandwidth (next week probably).
However, I hoped to bypass the problem momentarily by simply adding the option:
```
    restapi:
      ...
      verify_client: none
```

Reading at the doc:
https://patroni.readthedocs.io/en/latest/SETTINGS.html

my understanding was that no client certs are verified so no hostname check is done. The option should disable this verification for all the API (safe and unsafe), instead if I run the command switchover I got the message below. Why does this happen?
```
2021-09-16 16:22:47,317 - ERROR - Certificate did not match expected hostname: 172.16.230.6. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb_patroni_api_server'),)), 'issuer': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb root certificate'),)), 'version': 3, 'serialNumber': 'E152A4426EBE7892', 'notBefore': 'Sep 11 09:05:43 2021 GMT', 'notAfter': 'Sep 11 09:05:43 2022 GMT', 'subjectAltName': (('DNS', '*.cf-db.svc.cluster.local'), ('DNS', 'localhost'), ('IP Address', '127.0.0.1'))}
2021-09-16 16:22:47,319 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '172.16.230.6' doesn't match either of '*.cf-db.svc.cluster.local', 'localhost', '127.0.0.1'",),)': /switchover
2021-09-16 16:22:47,330 - ERROR - Certificate did not match expected hostname: 172.16.230.6. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb_patroni_api_server'),)), 'issuer': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb root certificate'),)), 'version': 3, 'serialNumber': 'E152A4426EBE7892', 'notBefore': 'Sep 11 09:05:43 2021 GMT', 'notAfter': 'Sep 11 09:05:43 2022 GMT', 'subjectAltName': (('DNS', '*.cf-db.svc.cluster.local'), ('DNS', 'localhost'), ('IP Address', '127.0.0.1'))}
2021-09-16 16:22:47,367 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '172.16.230.6' doesn't match either of '*.cf-db.svc.cluster.local', 'localhost', '127.0.0.1'",),)': /switchover
2021-09-16 16:22:47,379 - ERROR - Certificate did not match expected hostname: 172.16.230.6. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb_patroni_api_server'),)), 'issuer': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb root certificate'),)), 'version': 3, 'serialNumber': 'E152A4426EBE7892', 'notBefore': 'Sep 11 09:05:43 2021 GMT', 'notAfter': 'Sep 11 09:05:43 2022 GMT', 'subjectAltName': (('DNS', '*.cf-db.svc.cluster.local'), ('DNS', 'localhost'), ('IP Address', '127.0.0.1'))}
2021-09-16 16:22:47,417 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '172.16.230.6' doesn't match either of '*.cf-db.svc.cluster.local', 'localhost', '127.0.0.1'",),)': /switchover
2021-09-16 16:22:47,467 - ERROR - Certificate did not match expected hostname: 172.16.230.6. Certificate: {'subject': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb_patroni_api_server'),)), 'issuer': ((('countryName', 'US'),), (('stateOrProvinceName', 'TX'),), (('localityName', 'Austin'),), (('organizationName', 'IBM'),), (('organizationalUnitName', 'IBM Cloud'),), (('commonName', 'ccdb root certificate'),)), 'version': 3, 'serialNumber': 'E152A4426EBE7892', 'notBefore': 'Sep 11 09:05:43 2021 GMT', 'notAfter': 'Sep 11 09:05:43 2022 GMT', 'subjectAltName': (('DNS', '*.cf-db.svc.cluster.local'), ('DNS', 'localhost'), ('IP Address', '127.0.0.1'))}
2021-09-16 16:22:47,469 - ERROR - None
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 360, in connect
    _match_hostname(cert, self.assert_hostname or hostname)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 370, in _match_hostname
    match_hostname(cert, asserted_hostname)
  File "/usr/lib/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname '172.16.230.6' doesn't match either of '*.cf-db.svc.cluster.local', 'localhost', '127.0.0.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 719, in _do_failover_or_switchover
    r = request_patroni(member, 'post', action, failover_value)
  File "/usr/local/lib/python3.6/dist-packages/patroni/ctl.py", line 171, in request_patroni
    return request_executor(member, method, endpoint, data)
  File "/usr/local/lib/python3.6/dist-packages/patroni/request.py", line 53, in __call__
    return self.request(method, url, data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/patroni/request.py", line 46, in request
    return self._pool.request(method.upper(), url, body=body, **kwargs)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 70, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 322, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.16.230.6', port=8008): Max retries exceeded with url: /switchover (Caused by SSLError(CertificateError("hostname '172.16.230.6' doesn't match either of '*.cf-db.svc.cluster.local', 'localhost', '127.0.0.1'",),))
2021-09-16 16:22:47,477 - WARNING - Failing over to DCS
2021-09-16 16:22:47.47828 Could not switchover using Patroni api, falling back to DCS
```

**Comment by CyberDem0n** [comment]
The error you get is from patronictl, which btw has its own configuration: https://patroni.readthedocs.io/en/latest/SETTINGS.html#ctl

**Comment by sasadangelo** [comment]
Thank you. At the moment I solved with:
```
ctl:
  insecure: true
```

but the following WARNING appears:
```
2021-09-16 17:22:32,010 - WARNING - /usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

Adding the following:
```
ctl:
  cacert: /run/certs/patroni_api_server.ca_cert
  certfile: /run/certs/patroni_api_server.public_cert
  keyfile: /run/certs/patroni_api_server.private_key
```

does not produce any effect (same error).
So it seems that unless I use ``ìnsecure=true``` there is no way to have ```patronictl switchover``` working in SSL (without client verification and hostname check).
Can you confirm this?

PS
if I am correct the only solution I see is to implement Hostname instead of IPs in connect_address.

**Comment by CyberDem0n** [comment]
You can try:
```yaml
ctl:
  insecure: true
  certfile: /run/certs/patroni_api_server.public_cert
  keyfile: /run/certs/patroni_api_server.private_key
```

It will use client certificates, but will not validate the API cert (although, there will be a warning).
In theory, it is not hard to implement yet another switch in Patroni config that will disable hostname validation: https://urllib3.readthedocs.io/en/stable/reference/urllib3.connectionpool.html?highlight=assert_hostname#urllib3.HTTPSConnectionPool

**Comment by sasadangelo** [comment]
It doesn't work. The Patroni cluster goes in strange states:
```
+ Cluster: cfdb-ccdb (7008794415106429000) ---+----+-----------+
| Member         | Host                  | Role        | State       | TL   | Lag in MB  |
+-------------+---------------+---------+---------+----+-----------+
| cfdb-ccdb-0 | 172.16.230.17 | Replica | stopped |    |   unknown           |
+-------------+---------------+---------+---------+----+-----------+
```

sometimes only two nodes up and other strange stuff. It's hard to debug this issue. In Patroni doc there is a flow chart on how it works, but there should be a sort of Troubleshooting guide to help people debug problems.
At the moment it's ok the warning.
I don't have at the moment bandwidth to implement a new API and since we need (for several reasons) hostnames probably the solution is the patch you mentioned above. I put it in my backlog and next month we will try to understand what to do.
For the moment thank you for the support.

**Comment by sasadangelo** [comment]
> There is a function that builds the instance metadata dict, you can set the 'ip' to a custom value from the CONNECT_ADDRESS env variable.

@CyberDem0n going back to your suggestion I was working on this item because when everything is in SSL you need absolutely hostname due to host verification. However, I think there is another method to use the hostname as IP. Here is what I did:

```
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              #fieldPath: status.podIP
              fieldPath: metadata.name
        - name: POD_IP
          value: "$(POD_NAME).cfdb-ccdb     <-- hostname.servicename
```

since POD_IP is used in Spilo code it will be solved, for each Pod, in:
* cfdb-ccdb-0.cfdb-ccdb
* cfdb-ccdb-0.cfdb-ccdb
* cfdb-ccdb-0.cfdb-ccdb

And this hostname are correctly resolved with Pod IPs since it is <pod name>.<service name>.svc.cluster.local. Since svc.cluster.local in the search of resolv.conf the hostname are correctly solved.

The problem now is that code that update the Service endpoint with the master IP doesn't work anymore because it now has a hostname instead of an IP:
```
2021-09-21 08:05:20,750 WARNING: Unable to change service endpoints: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Endpoints \"cfdb-ccdb\" is invalid: [subsets[0].addresses[0].ip: Invalid value: \"cfdb-ccdb-0.cfdb-ccdb\": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff), subsets[0].addresses[0].ip: Invalid value: \"cfdb-ccdb-0.cfdb-ccdb\": must be a valid IP address]","reason":"Invalid","details":{"name":"cfdb-ccdb","kind":"Endpoints","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"cfdb-ccdb-0.cfdb-ccdb\": must be a valid IP address, (e.g. 10.9.8.7 or 2001:db8::ffff)","field":"subsets[0].addresses[0].ip"},{"reason":"FieldValueInvalid","message":"Invalid value: \"cfdb-ccdb-0.cfdb-ccdb\": must be a valid IP address","field":"subsets[0].addresses[0].ip"}]},"code":422}
```

What I can do to solve the problem?

**Comment by CyberDem0n** [comment]
> What I can do to solve the problem?

Introduce a new env. The POD_IP is used in several places and assumes that it contains the IP.

**Comment by sasadangelo** [comment]
Ok, but it's not clear to me how to update the function ```get_instance_metadata```. As said above, I understand that I should do something like this:

```
if MY_NEW_ENV exist:
    metadata['ip'] = os.environ.get('MY_NEW_ENV', metadata['ip']) 
```

but I don't know where to put it, it's interaction with the USE_KUBERNETES variable. In addition, if I assign to metadata['ip'] a hostname, there could be a problem somewhere else? Is there an assumption that metadata['ip'] contains always an IP?

**Comment by sasadangelo** [comment]
I think I got your point. POD_IP is used here too:
https://github.com/zalando/spilo/blob/4c02a6dd1970307d34001089106b8417fa0554c2/postgres-appliance/scripts/callback_role.py#L66-L74

this is where the Endpoint IP change. This is the reason why you told me to use a different variable. So I can do something like this:

```
def get_instance_metadata(provider):
    metadata = {'ip': socket.getaddrinfo(socket.gethostname(), 0, socket.AF_UNSPEC, socket.SOCK_STREAM, 0)[0][4][0],
                'id': socket.gethostname(),
                'zone': 'local'}

    if USE_KUBERNETES:
        if MY_NEW_ENV exist:
            metadata['ip'] = os.environ.get('MY_NEW_ENV', metadata['ip'])
        else:
            metadata['ip'] = os.environ.get('POD_IP', metadata['ip'])
```

Do you agree this is the correct fix to do? Do you think this could be an acceptable fix for the official Spilo code? 
If the answer is no, I will use the official Spilo image on top of which I will apply a patch before our build.

**Comment by CyberDem0n** [comment]
Templates also should be updated.
Everything was build in order to rely only on IPs in order to eliminate possible DNS issues (they are biting very hard).

**Comment by sasadangelo** [comment]
Ok, yes I know DNS sometimes is a pain. However, in a serious production environment, SSL is a must. I am curious how your team implements it. I mean, I see few possible solutions:
* use SSL only at an Ingress level and let all internal communication no SSL;
* use static or floating IP;

**Comment by sasadangelo** [comment]
I have another doubt but before talking about it, I need to understand if this is a general fix that is good enough to be included in Spilo's official code or it is just for our needs.
I am asking this because your suggestion (if this is a general fix) is that if I change the TEMPLATE with something like this:

```
restapi:
  listen: ':{{APIPORT}}'
  connect_address: {{CONNECT_ADDRESS}}:{{APIPORT}}
```

what happens if a user doesn't define the CONNECT_ADDRESS variable?

I understand that the solution relies on IP address and your team want to avoid leveraging DNS. But the issues you are talking about is something you experienced at the setup level or simply it is something you noticed monitoring the CoreDNS (or whatever DNS you used in the past)? Moreover, since SSL is a must in a production environment how did you implement it in your system? Do you use static or floating IPs? Do you use SSL only at Ingress level?

**Comment by CyberDem0n** [comment]
> what happens if a user doesn't define the CONNECT_ADDRESS variable?


Patroni docs are very explicit about it: https://patroni.readthedocs.io/en/latest/SETTINGS.html#rest-api

If REST API isn't accessible, leader election will not work as expected.

**Comment by sasadangelo** [comment]
Hi @CyberDem0n 

I did the change in my fork (on top of the recent PR merges):
https://github.com/sasadangelo/spilo/commit/6e45245543659d8c4ef9f6543d4563a7084fdf5e

Please let me know your thoughts. Do you think it is a fix that could be included in the official Spilo code?

**Comment by CyberDem0n** [comment]
> Do you think it is a fix that could be included in the official Spilo code?

Yes, but a few adjustments are needed:
1. You override the `metadata['ip']` here https://github.com/sasadangelo/spilo/commit/6e45245543659d8c4ef9f6543d4563a7084fdf5e#diff-e4dcf964214d58d733ae9874d4a2ab4b8e9eb99213307e1666af5dad21a326bbR427 and it is wrong
2. Maybe you can do the same for `postgresql.connect_address`. After that you can use `verify-full` for cross-node communication.

**Comment by sasadangelo** [comment]
Hi @CyberDem0n 

Thank you for your reply. I know it seems an override but it isn't.
You must read code like this:
```
metadata = {'ip': socket.getaddrinfo(socket.gethostname(), 0, socket.AF_UNSPEC, socket.SOCK_STREAM, 0)[0][4][0],
                'id': socket.gethostname(),
                'zone': 'local'}
```

```metadata['ip']``` initially is an IP.

This instruction:
```
metadata['ip'] = os.environ.get('POD_IP', metadata['ip'])
```

means:
```
if POD_IP is defined:
    metadata['ip'] = os.environ.get('POD_IP')
else:
    leave as it is
```

This instruction:
```
metadata['ip'] = os.environ.get('CONNECT_ADDRESS', metadata['ip'])
```

means:
```
if CONNECT_ADDRESS is defined:
    metadata['ip'] = os.environ.get('CONNECT_ADDRESS')
else:
    leave as it is ... this means metadata['ip']=IP or metadata['ip']=POD_IP depending on the result of previous instruction.
```

However, you're right that a few adjustments are needed. For example, I think this is incorrect in ```TEMPLATE```:
```
restapi:
   ...
  connect_address: {{CONNECT_ADDRESS}}:{{APIPORT}}
```

we need something that if CONNECT_ADDRESS is not passed the previous value ```'{{instance_data.ip}}'``` should be used, but I don't know how to do that in code. In fact, in a test, I tried just to start a Spilo container in docker with docker run and I got an error about ```CONNECT_ADDRESS``` not being defined, this never happened before.

**Comment by CyberDem0n** [comment]
```python
metadata['ip'] = os.environ.get('CONNECT_ADDRESS', metadata['ip'])
```

It clearly changing the value of `metadata['ip']` if `CONNECT_ADDRESS` env is set, what is undesirable, because for instance the `instance_data.ip` is used in the `postgresql.connect_address`.

**Comment by sasadangelo** [comment]
Yes, this is what I did and it works fine. What could be the drawback?

>There is a function that builds the instance metadata dict, you can set the 'ip' to a custom value from CONNECT_ADDRESS env variable.

in this message above you said "you can set the 'ip' to a ..." I imagined you meant set metdadata['ip']. Was my understanding wrong? If so, can you help me to find a better solution?

**Comment by CyberDem0n** [comment]
> What could be the drawback?

The `instance_data.ip` is used in the `postgresql.connect_address` and in the https://github.com/zalando/spilo/blob/3612e7f54284c8394bb7a4fd1097a0ef63e7c154/postgres-appliance/scripts/configure_spilo.py#L695

While the first one is something that you want, it should be done explicitly, as it was done for restapi.
The second one will in fact break setups that use K8s API and Endpoints for leader elections.

> can you help me to find a better solution?

`metadata['ip'] = os.environ.get('CONNECT_ADDRESS', metadata['ip'])` should become `placeholders.setdefault('CONNECT_ADDRESS', placeholders['instance_data']['ip'])` and placed here: https://github.com/zalando/spilo/blob/3612e7f54284c8394bb7a4fd1097a0ef63e7c154/postgres-appliance/scripts/configure_spilo.py#L656

**Comment by sasadangelo** [comment]
OK thank you for your help. This is the final commit: https://github.com/sasadangelo/spilo/commit/ac09361ec51d4b05d3b2148c5aada154bc075a15
I am going to start some tests and I'll let you know the results.
However, it's not clear to me what would have happened if even ```postgresql.connect_address``` would be equal to CONNECT_ADDRESS. I always assume the hostname was correctly resolved by CoreDNS. Correct?

**Comment by sasadangelo** [comment]
Hi @CyberDem0n 

I did some tests and as expected when I defined the environment variable like this:
```
        - name: CONNECT_ADDRESS
          value: "$(POD_NAME).cfdb-ccdb"
```

I got in ```postgres.yml``` the following:
```
postgresql:
  ...
  connect_address: 172.16.230.49:5432
restapi:
  ...
  connect_address: cfdb-ccdb-0.cfdb-ccdb:8008
```

As a result when I run ```patronictl list``` this result surprised me because I see IPs instead of hostnames:
```
+ Cluster: cfdb-ccdb (7012976291421675615) -----------------+----+-----------+
| Member      | Host           | Role    | State            | TL | Lag in MB |
+-------------+----------------+---------+------------------+----+-----------+
| cfdb-ccdb-0 | 172.16.230.49  | Leader  | running          |  3 |           |
| cfdb-ccdb-1 | 172.16.140.55  | Replica | running |    |   unknown |
| cfdb-ccdb-2 | 172.16.235.225 | Replica | running |    |   unknown |
+-------------+----------------+---------+------------------+----+-----------+
```

It is clear now that that ```Host```comes from the PostgreSQL connect_address parameter and not from the REST API one. I think you already knew this. But I am asking why having ```postgresql.connect_address``` as hostname is undesirable. I know Patroni design is based on IP but I was wondering if PostgreSQL SSL connection could be affected by the same problem of REST API one (hostname validation).

**Comment by CyberDem0n** [comment]
> and not from the REST API one. I think you already knew this.

Yes

> I know Patroni design is based on IP

No, Patroni doesn't care. There should be just something that is reachable from the "outside".

> if PostgreSQL SSL connection could be affected by the same problem of REST API one (hostname validation).

In Postgres you can use `verify-ca` and it will not check hostnames. With `verify-full` it will check everything.

> I was wondering if could make sense to have two variables:

Whatever works for you.

**Comment by sasadangelo** [comment]
> Whatever works for you.
Ok, but it should be acceptable by the general Spilo design and make sense to submit a PR for this.
The main reason I ask this is that I want to exclude the risk to fork my project. I mean, I am working now on my fork to avoid that the inclusion of PR in the official code slow down my activities, but for each change in Spilo my goal is to try to include it in the official code to avoid, in the future, the need to include fixes in my forks.

**Comment by sasadangelo** [comment]
I submit this PR https://github.com/zalando/spilo/pull/640 for the issue.

**Comment by sasadangelo** [comment]
I noticed [my PR was merged](https://github.com/zalando/spilo/commit/e3ce5702ee93fb6c2a21e4891e557f9c95acd861). I close this issue.
