### ISSUE TITLE
yaml.reader.ReaderError: unacceptable character #x000e: special characters are not allowed

### ISSUE THREAD

**Issue by brunoarruda** [zalando/spilo#730]
```yaml
versions:
- spilo-14:2.1-p5
- 
``` 

Hi, 

I'm trying to configure a cluster replica with Postgre-Operator. On primary cluster, deploy went okay and I am able to connect. On secundary cluster, the spilo master node is crashing. The logs of the pod:

```python
# 2022-05-24 16:06:30,466 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
# 2022-05-24 16:06:32,476 - bootstrapping - INFO - Could not connect to 169.254.169.254, assuming local Docker setup
# 2022-05-24 16:06:32,478 - bootstrapping - INFO - No meta-data available for this provider
# 2022-05-24 16:06:32,486 - bootstrapping - INFO - Looks like your running local
Traceback (most recent call last):
  File "/scripts/configure_spilo.py", line 1112, in <module>
    main()
  File "/scripts/configure_spilo.py", line 1013, in main
    config = yaml.load(pystache_render(TEMPLATE, placeholders))
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/lib/python3/dist-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x000e: special characters are not allowed
  in "<unicode string>", position 3317
```

here are the environment values (password and STANDBY_HOST supressed):

```bash
POSTGRES_OPERATOR_UI_SERVICE_HOST=10.107.95.21
LC_ALL=C.UTF-8
STANDBY_HOST=
POSTGRES_OPERATOR_SERVICE_PORT=8080
POSTGRES_OPERATOR_UI_PORT_80_TCP_PROTO=tcp
POSTGRES_OPERATOR_UI_PORT_80_TCP_ADDR=10.107.95.21
POSTGRES_OPERATOR_SERVICE_HOST=10.103.167.156
LESSCLOSE=/usr/bin/lesspipe %s %s
KUBERNETES_SCOPE_LABEL=cluster-name
RW_DIR=/run
�Z�;�~�H�=u�8|��zY=��♫�↕]/      �∟�z�▬�;"       ▼���Ru�@Ш

LANG=C.UTF-8
HOSTNAME=acid-cluster-0
SPILO_CONFIGURATION={"postgresql":{},"bootstrap":{"initdb":[{"auth-host":"md5"},{"auth-local":"trust"}],"users":{"zalandos":{"password":"","options":["CREATEDB","NOLOGIN"]}},"dcs":{}}}
EDITOR=editor
PLPROFILER=REL4_1
HUMAN_ROLE=zalandos
PGROOT=/home/postgres/pgdata/pgroot
PAM_OAUTH2=https://info.example.com/oauth2/tokeninfo?access_token= uid realm=/employees
ACID_CLUSTER_SERVICE_PORT=5432
DCS_ENABLE_KUBERNETES_API=true
POSTGRES_OPERATOR_PORT_8080_TCP_ADDR=10.103.167.156
PGUSER_SUPERUSER=postgres
POSTGRES_OPERATOR_UI_PORT_80_TCP_PORT=80
ACID_CLUSTER_REPL_SERVICE_HOST=10.104.123.238
POSTGRES_OPERATOR_PORT=tcp://10.103.167.156:8080
LOG_ENV_DIR=/run/etc/log.d/env
POSTGRES_OPERATOR_PORT_8080_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PROTO=tcp
POSTGIS_LEGACY=3.2
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
POSTGRES_OPERATOR_UI_SERVICE_PORT=80
PGVERSION=14
PG_AUTH_MON_COMMIT=437435b4e2de32a820e86973f6934ec849a768e0
ACID_CLUSTER_REPL_SERVICE_PORT=5432
KUBERNETES_PORT=tcp://10.96.0.1:443
PWD=/home/postgres
KUBERNETES_ROLE_LABEL=spilo-role
PGHOME=/home/postgres
HOME=/root
KUBERNETES_SERVICE_PORT_HTTPS=443
PGDATA=/home/postgres/pgdata/pgroot/data
KUBERNETES_PORT_443_TCP_PORT=443
DEMO=false
ACID_CLUSTER_PORT_5432_TCP_ADDR=10.96.129.83
SET_USER=REL3_0_0
WALE_VERSION=1.1.1
ACID_CLUSTER_PORT_5432_TCP_PROTO=tcp
ACID_CLUSTER_REPL_PORT=tcp://10.104.123.238:5432
ACID_CLUSTER_SERVICE_PORT_POSTGRESQL=5432
PG_MON_COMMIT=54fbdcc3cfe7e2a626bd96dda644d9a0c6866b58
STANDBY_PORT=5432
POSTGRES_OPERATOR_PORT_8080_TCP_PORT=8080
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
ACID_CLUSTER_PORT_5432_TCP=tcp://10.96.129.83:5432
TIMESCALEDB=1.7.5 2.3.1 2.6.1
ACID_CLUSTER_REPL_PORT_5432_TCP_PORT=5432
BG_MON_COMMIT=098b4857d1e88862439c0f02a6031e9fb78e5ef2
KUBERNETES_LABELS={"application":"spilo"}
ACID_CLUSTER_SERVICE_HOST=10.96.129.83
TERM=linux
POSTGRES_OPERATOR_UI_PORT_80_TCP=tcp://10.107.95.21:80
POSTGRES_OPERATOR_UI_PORT=tcp://10.107.95.21:80
PGPASSWORD_SUPERUSER=
PGUSER_STANDBY=standby
PATRONIVERSION=2.1.3
ACID_CLUSTER_REPL_PORT_5432_TCP_ADDR=10.104.123.238
ACID_CLUSTER_REPL_PORT_5432_TCP_PROTO=tcp
SCOPE=acid-cluster
SHLVL=1
ACID_CLUSTER_REPL_SERVICE_PORT_POSTGRESQL=5432
POD_NAMESPACE=cedro-control
KUBERNETES_SERVICE_PORT=443
WALE_ENV_DIR=/run/etc/wal-e.d/env
POSTGIS_VERSION=3.2
PLANTUNER_COMMIT=800d81bc85da64ff3ef66e12aed1d4e1e54fc006
PGLOG=/home/postgres/pgdata/pgroot/pg_log
POSTGRES_OPERATOR_PORT_8080_TCP=tcp://10.103.167.156:8080
PG_PERMISSIONS_COMMIT=314b9359e3d77c0b2ef7dbbde97fa4be80e31925
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/14/bin
POD_IP=10.244.0.105
KUBERNETES_SERVICE_HOST=10.96.0.1
ACID_CLUSTER_PORT_5432_TCP_PORT=5432
ACID_CLUSTER_PORT=tcp://10.96.129.83:5432
LESSOPEN=| /usr/bin/lesspipe %s
ACID_CLUSTER_REPL_PORT_5432_TCP=tcp://10.104.123.238:5432
_=/usr/bin/env
```

that is the full log of the image. It keeps trying and failing.

I was not able to find any issue related to that problem, so I'm trying contact here to get any clue about what could be wrong.

**Comment by CyberDem0n** [comment]
There is some garbage in environment:

```
RW_DIR=/run
�Z�;�~�H�=u�8|��zY=��♫�↕]/      �∟�z�▬�;"       ▼���Ru�@Ш

LANG=C.UTF-8
```

And it somehow affects template render: https://github.com/zalando/spilo/blob/23f712d1d5eed8ccd4da02b5f1cc5ae40afbb7b7/postgres-appliance/scripts/configure_spilo.py#L170-L383

You need to check what pystache_render() function returns: https://github.com/zalando/spilo/blob/23f712d1d5eed8ccd4da02b5f1cc5ae40afbb7b7/postgres-appliance/scripts/configure_spilo.py#L686-L688

**Comment by brunoarruda** [comment]
Thanks for your quick reply @CyberDem0n 

Well, because of the deadline related to the project, I destroyed that k0s cluster and built it again from scratch. Everything went fine with the new environment and I was not able to reproduce the issue anymore.

I will close this issue.

Best regards!
