### ISSUE TITLE
docker run shows: env: ‘/scripts/patroni_wait.sh’: Permission denied

### ISSUE THREAD

**Issue by yinan8128** [zalando/spilo#796]
[docker_spilo_build.log](https://github.com/zalando/spilo/files/10009468/docker_spilo_build.log)
Hi,

Once we setup docker env, shows: env: ‘/scripts/patroni_wait.sh’: Permission denied

1. cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

2. docker --version
Docker version 20.10.20, build 9fdeb9c

3. git clone https://github.com/zalando/spilo.git
4. cd spilo/postgres-appliance/
5. export YOUR_TAG=spiloimage

6. docker build --tag $YOUR_TAG .
please check attached docker_spilo_build.log
[docker_spilo_build.log](https://github.com/zalando/spilo/files/10009474/docker_spilo_build.log)

7. docker run -it spiloimage:latest
2022-11-15 05:07:09,208 - bootstrapping - INFO - Figuring out my environment (Google? AWS? Openstack? Local?)
2022-11-15 05:07:09,284 - bootstrapping - INFO - No meta-data available for this provider
2022-11-15 05:07:09,285 - bootstrapping - INFO - Looks like you are running unsupported
2022-11-15 05:07:09,343 - bootstrapping - INFO - Configuring standby-cluster
2022-11-15 05:07:09,344 - bootstrapping - INFO - Configuring log
2022-11-15 05:07:09,344 - bootstrapping - INFO - Configuring certificate
2022-11-15 05:07:09,344 - bootstrapping - INFO - Generating ssl self-signed certificate
2022-11-15 05:07:09,648 - bootstrapping - INFO - Configuring pgbouncer
2022-11-15 05:07:09,648 - bootstrapping - INFO - No PGBOUNCER_CONFIGURATION was specified, skipping
2022-11-15 05:07:09,648 - bootstrapping - INFO - Configuring pgqd
2022-11-15 05:07:09,649 - bootstrapping - INFO - Configuring wal-e
2022-11-15 05:07:09,649 - bootstrapping - INFO - Configuring patroni
2022-11-15 05:07:09,660 - bootstrapping - INFO - Writing to file /run/postgres.yml
2022-11-15 05:07:09,660 - bootstrapping - INFO - Configuring crontab
2022-11-15 05:07:09,660 - bootstrapping - INFO - Skipping creation of renice cron job due to lack of SYS_NICE capability
2022-11-15 05:07:09,661 - bootstrapping - INFO - Configuring bootstrap
2022-11-15 05:07:09,661 - bootstrapping - INFO - Configuring pam-oauth2
2022-11-15 05:07:09,661 - bootstrapping - INFO - No PAM_OAUTH2 configuration was specified, skipping
env: ‘/scripts/patroni_wait.sh’: Permission denied
2022-11-15 05:07:11,047 INFO: Failed to import patroni.dcs.raft
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 143, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 135, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 98, in abstract_main
    controller = cls(config)
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 25, in __init__
    self.dcs = get_dcs(self.config)
  File "/usr/local/lib/python3.6/dist-packages/patroni/dcs/__init__.py", line 111, in get_dcs
    Available implementations: """ + ', '.join(sorted(set(available_implementations))))
patroni.exceptions.PatroniFatalException: 'Can not find suitable configuration of distributed configuration store\nAvailable implementations: consul, etcd, etcd3, exhibitor, kubernetes, zookeeper'
/etc/runit/runsvdir/default/patroni: finished with code=1 signal=0
/etc/runit/runsvdir/default/patroni: sleeping 30 seconds
env: ‘/scripts/patroni_wait.sh’: Permission denied
env: ‘/scripts/patroni_wait.sh’: Permission denied
env: ‘/scripts/patroni_wait.sh’: Permission denied

Could you please help check how to fix and to let the docker env work please? Thanks

**Comment by yinan8128** [comment]
Hi

Is there any update please? Thank you

**Comment by yinan8128** [comment]
Hi 

How about this please? As there is problem in the docker env, we don't have the sample to check to proceed

**Comment by yinan8128** [comment]
Hi

How about this please? As there is problem in the docker env, we don't have the sample to check to proceed

**Comment by yinan8128** [comment]
Hi

I have tried several times, still face the same error, as already attached the steps to reproduce, could you please help check? Or any other information need I provide please? Thank you

**Comment by yinan8128** [comment]
Hi

I have tried several times, still face the same error, just updated the steps and attached log file to reproduce, could you please help check? Thank you
