### ISSUE TITLE
Postgres11 pods in crashloop with Postgres11 and DEMO=true

### ISSUE THREAD

**Issue by nethi** [zalando/spilo#799]
Hi,

I am trying to create a postgres11 production image with the following arguments with the intent to use this as "dockerImage" override with Zalando operator.  I chose "DEMO=true" to have a minimal image in kubernetes, as per documentation:

docker build -t spilo-postgres11:latest 
  --build-arg "PGVERSION=11" 
  --build-arg "WITH_PERL=false" 
  --build-arg "COMPRESS=false" 
  --build-arg "PGOLDVERSIONS=""" 
  --build-arg "DEMO=true" .
  
Image was successfully built. Then I created postgres cluster using Zalando postgres operator (config attached).
Postgres11 pod is in crashloop. It is failing with this error:

2022-11-10 15:03:54 UTC [278]: [1-1] 636d12da.116 0     FATAL:  could not access file "pgextwlist": No such file or directory

Looking into the pod, I don't see "plugins" directory in /usr/lib/postgres/11/lib and hence the missing file "pgextwlist.so "

Dockerfile seems to skip installation of this if DEMO=true.
https://github.com/zalando/spilo/blob/99aa59b4b19f329359448fd2d6df1dae2c0a45c4/postgres-appliance/Dockerfile#L203 

Am I misunderstanding "DEMO" argument or am I missing some other step ?

Thanks
Ramesh

```
2022-11-10 15:03:51,274 WARNING: Kubernetes RBAC doesn't allow GET access to the 'kubernetes' endpoint in the 'default' namespace. Disabling 'bypass_api_service'.
2022-11-10 15:03:51,299 INFO: No PostgreSQL configuration items changed, nothing to reload.
2022-11-10 15:03:51,305 INFO: Lock owner: None; I am acid-my-postgres-0
2022-11-10 15:03:51,530 INFO: trying to bootstrap a new cluster
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/postgres/pgdata/pgroot/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/lib/postgresql/11/bin/pg_ctl -D /home/postgres/pgdata/pgroot/data -l logfile start

2022-11-10 15:03:54 UTC [278]: [1-1] 636d12da.116 0     FATAL:  could not access file "pgextwlist": No such file or directory
2022-11-10 15:03:54 UTC [278]: [2-1] 636d12da.116 0     LOG:  database system is shut down
2022-11-10 15:03:54,975 INFO: postmaster pid=278
/var/run/postgresql:5432 - no response
2022-11-10 15:03:56,051 ERROR: postmaster is not running
2022-11-10 15:03:56,052 INFO: removing initialize key after failed attempt to bootstrap the cluster
2022-11-10 15:03:56,111 INFO: renaming data directory to /home/postgres/pgdata/pgroot/data_2022-11-10-15-03-56
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 143, in main
    return patroni_main()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 135, in patroni_main
    abstract_main(Patroni, schema)
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 100, in abstract_main
    controller.run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 105, in run
    super(Patroni, self).run()
  File "/usr/local/lib/python3.6/dist-packages/patroni/daemon.py", line 59, in run
    self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/__main__.py", line 108, in _run_cycle
    logger.info(self.ha.run_cycle())
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1514, in run_cycle
    info = self._run_cycle()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1388, in _run_cycle
    return self.post_bootstrap()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1280, in post_bootstrap
    self.cancel_initialization()
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 1273, in cancel_initialization
    raise PatroniFatalException('Failed to bootstrap cluster')
patroni.exceptions.PatroniFatalException: 'Failed to bootstrap cluster'
/etc/runit/runsvdir/default/patroni: finished with code=1 signal=0
/etc/runit/runsvdir/default/patroni: exceeded maximum number of restarts 5
stopping /etc/runit/runsvdir/default/patroni
timeout: finish: .: (pid 280) 13s, want down

```

**Comment by hughcapet** [comment]
This is indeed a bug (pgextwlist should be installed unconditionally), we will fix it shortly. Thank you for reporting this!

**Comment by nethi** [comment]
Verified that it now works fine with demo=true.
