### ISSUE TITLE
No logging of postgresql after Patroni was restarted

### ISSUE THREAD

**Issue by feikesteenbergen** [zalando/spilo#82]
Situation:

patroni died
postgres kept running
patroni was respawned, no action - leader was still the same

After this, no logging of PostgreSQL was visible

``` text
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]: 2016-07-27 14:51:58,099 INFO: Starting new HTTP connection (1): 172.31.141.11
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]: 2016-07-27 14:51:58,610 INFO: closed patroni connection to the postgresql cluster
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]: Traceback (most recent call last):
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:   File "/usr/local/bin/patroni", line 9, in <module>
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:     load_entry_point('patroni==0.90', 'console_scripts', 'patroni')()
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:   File "/usr/local/lib/python2.7/dist-packages/patroni/__init__.py", line 105, in main
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:     patroni.postgresql.stop(checkpoint=False)
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 398, in stop
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:     if not self.is_running():
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:   File "/usr/local/lib/python2.7/dist-packages/patroni/postgresql.py", line 317, in is_running
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:     return subprocess.call(' '.join(self._pg_ctl) + ' status > /dev/null 2>&1', shell=True) == 0
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:   File "/usr/lib/python2.7/subprocess.py", line 522, in call
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:     return Popen(*popenargs, **kwargs).wait()
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:     errread, errwrite)
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:   File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]:     self.pid = os.fork()
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]: OSError: [Errno 12] Cannot allocate memory
Jul 27 14:51:58 ip-172-31-157-143 docker/f7d1ae09a079[884]: 2016-07-27 14:51:58,765 INFO exited: patroni (exit status 1; not expected)
Jul 27 14:51:59 ip-172-31-157-143 docker/f7d1ae09a079[884]: 2016-07-27 14:51:59,771 INFO spawned: 'patroni' with pid 30418
```

**Comment by feikesteenbergen** [comment]
Theory:

Patroni spawns Postgres, stdout is passed via Patroni to supervisord
Patroni died, therefore pg stdout was not directed to stdout of supervisord

By restarting postgres (using Patroni) we saw the logging being restored.

**Comment by LappleApple** [comment]
Hey @CyberDem0n @alexeyklyukin, is this issue from July 2016 still relevant?
